-- HOTFIX for 20260817: a no-show could downgrade themselves to a withdrawal.
--
-- 20260817 set the no-show penalty at 25 points, above the worst withdrawal
-- tier (15), so that failing to turn up costs more than saying so in advance.
-- But worker_withdraw_from_shift never checked whether the shift had already
-- started, and employer_mark_no_show only accepts an application still in
-- status 'accepted'.
--
-- So the cheaper path was: don't turn up, then withdraw before the employer
-- gets round to marking you. 0 hours notice = 15 points, and the application
-- is now 'withdrawn' so the 25-point mark can never be applied. The worse
-- behaviour ended up cheaper -- exactly the inversion 20260817 was written to
-- remove.
--
-- Fix: withdrawal is refused once start_at has passed. It stays available up
-- to that moment, so genuine last-minute notice is still possible and still
-- reduces nothing but the employer's surprise. Afterwards the only honest
-- outcomes are "attended" or "did not attend", and that is the employer's
-- call, not the worker's.
--
-- Generated by patching the live definition from 20260815b -- only the new
-- precondition is inserted; every other line is byte-identical.

create or replace function public.worker_withdraw_from_shift(
  p_application_id uuid,
  p_reason text default null
)
returns public.applications
language plpgsql
security definer
set search_path = public
as $$
declare
  v_app record;
  v_shift record;
  v_notice_hours numeric;
  v_tier public.cancellation_tiers;
  v_penalty int;
  v_worker_name text;
  v_now timestamptz := now();
begin
  select a.id, a.worker_id, a.shift_id, a.status, a.withdrawn_at
  into v_app
  from public.applications a
  where a.id = p_application_id;

  if v_app.id is null then
    raise exception 'Application not found';
  end if;

  if v_app.worker_id is distinct from auth.uid() then
    raise exception 'Not authorized';
  end if;

  if v_app.status is distinct from 'accepted' then
    raise exception 'Only a confirmed booking can be withdrawn from';
  end if;

  select s.id, s.title, s.employer_id, s.start_at, s.status, s.headcount
  into v_shift
  from public.shifts s where s.id = v_app.shift_id;

  if v_shift.status = 'cancelled' then
    raise exception 'This shift was already cancelled';
  end if;

  -- Closes a self-downgrade route opened by 20260817. Once the shift has
  -- started, a worker who failed to turn up could withdraw (0 notice = 15
  -- points) BEFORE the employer marked them, and employer_mark_no_show only
  -- accepts status = 'accepted' -- so withdrawing first made the no-show
  -- unmarkable and swapped a 25-point penalty for a 15-point one. Cheaper for
  -- the worse behaviour, which inverts the incentive the no-show penalty
  -- exists to create.
  --
  -- Withdrawal stays open right up to start_at, so genuine last-minute notice
  -- is still possible and still worth giving. After that the only honest
  -- outcomes are "attended" or "did not attend", and the employer decides
  -- which.
  if v_shift.start_at <= v_now then
    raise exception 'This shift has already started, so it can no longer be withdrawn from. Contact the employer directly.';
  end if;

  v_notice_hours := greatest(extract(epoch from (v_shift.start_at - v_now)) / 3600.0, 0);
  v_tier := public.cancellation_tier_for('worker', v_notice_hours);
  v_penalty := coalesce(v_tier.reliability_penalty, 0);

  -- The status guard only permits worker withdrawal from 'pending'; this is a
  -- legitimate server-side path, so it sets the same trusted-write flag the
  -- guard already recognises rather than being widened for everyone.
  perform set_config('app.application_status_trusted_write', 'true', true);
  update public.applications
  set status = 'withdrawn',
      withdrawn_at = v_now,
      withdrawal_reason = nullif(trim(coalesce(p_reason, '')), ''),
      withdrawal_notice_hours = round(v_notice_hours, 2),
      withdrawal_penalty = v_penalty,
      updated_at = v_now
  where id = p_application_id
  returning * into v_app;
  perform set_config('app.application_status_trusted_write', 'false', true);

  -- Reputation is the deterrent, not a cash penalty. It is enforceable (no
  -- collection problem), it is visible to employers in the applicant pool,
  -- and it is proportionate -- see the plan notes on why fining casual
  -- workers is both hard to collect and regressive.
  -- NOTE ON THE COLUMN: 20260628_profiles.sql declares reliability_score as
  -- `int not null default 0`, but live rows hold 100.00 -- the type and default
  -- were changed out-of-band at some point and no migration in this repo
  -- records it (same drift class as shifts.status turning out to be an enum).
  -- greatest(...) is written to be correct either way.
  if v_penalty > 0 then
    perform set_config('app.reliability_trusted_write', 'true', true);
    update public.profiles
    set reliability_score = greatest(coalesce(reliability_score, 100) - v_penalty, 0)
    where id = v_app.worker_id;
    perform set_config('app.reliability_trusted_write', 'false', true);
  end if;

  select full_name into v_worker_name from public.profiles where id = v_app.worker_id;

  -- The employer's real problem is being unstaffed, not the money. Reopening
  -- the shift immediately is the part that actually helps: filled_count is
  -- recomputed by trg_sync_filled_count on the status change, and a shift that
  -- had been marked 'filled' becomes discoverable again so it can be refilled.
  if v_shift.status = 'filled' then
    update public.shifts set status = 'open', updated_at = v_now where id = v_shift.id;
  end if;

  insert into public.notifications (user_id, type, title, body, link, params)
  values (
    v_shift.employer_id,
    'worker_withdrew',
    'A worker withdrew',
    coalesce(v_worker_name, 'A worker') || ' withdrew from "' ||
      coalesce(v_shift.title, 'your shift') || '" with ' ||
      round(v_notice_hours) || ' hours notice. The slot is open again.',
    '/employer/shifts/' || v_shift.id,
    jsonb_build_object(
      'shift_title', coalesce(v_shift.title, 'your shift'),
      'worker_name', coalesce(v_worker_name, 'A worker'),
      'notice_hours', round(v_notice_hours),
      'reason', nullif(trim(coalesce(p_reason, '')), '')
    )
  );

  -- Tell everyone who applied to this shift and was not selected that a slot
  -- is free again. Refilling fast is worth more to the employer than any
  -- penalty collected from the worker who left.
  insert into public.notifications (user_id, type, title, body, link, params)
  select
    a.worker_id,
    'slot_reopened',
    'A slot reopened',
    'A slot has reopened on "' || coalesce(v_shift.title, 'a shift') || '". Apply again if you are still free.',
    '/worker/shifts/' || v_shift.id,
    jsonb_build_object('shift_title', coalesce(v_shift.title, 'a shift'))
  from public.applications a
  where a.shift_id = v_shift.id
    -- 'rejected' only. 'not_selected' is a NOTIFICATION type, not an
    -- application status -- notify_not_selected_when_filled sets those rows to
    -- 'rejected'. Using it here would have raised on an invalid enum value.
    and a.status = 'rejected'
    and a.worker_id is distinct from v_app.worker_id;

  return v_app;
end;
$$;

revoke all on function public.worker_withdraw_from_shift(uuid, text) from public;
grant execute on function public.worker_withdraw_from_shift(uuid, text) to authenticated;
