-- Convert the remaining notification types to carry `params`, so every
-- notification in the app renders in the reader's language (20260812c covered
-- shift_updated / shift_terms_changed / shift_cancelled).
--
-- EVERY function below was generated by patching its CURRENT definition, read
-- programmatically from the migration that last defined it. This is not
-- stylistic caution: a hand-transcribed first draft of
-- create_cancellation_payout silently changed the payout table name, dropped a
-- defense-in-depth guard, and replaced the multi-day occurrence hours
-- calculation with a naive end-minus-start. Only the notification INSERT is
-- touched in each -- the column list gains `params`, and a jsonb_build_object
-- is appended to the values. No other line differs.
--
-- EXCEPTION HANDLERS go only on the four PURE notifiers. After 20260812 took
-- shift editing down, the rule is that notifying must never abort the write
-- that triggered it -- but that only holds where notifying is ALL a function
-- does. The other five write real state (status cascades, payout deadlines,
-- payout rows) or are RPCs the app calls directly; swallowing an error there
-- would leave inconsistent state, which is worse than failing loudly.
--
-- VARIANTS: three notifications have conditional bodies (declined vs expired,
-- 50% payout vs showing up, dispute with vs without a reason). Rather than
-- freeze the branch as English prose, params carries a `variant` and the app
-- looks up `notif.<type>.<variant>.body`.
--
-- TIMESTAMPS travel as raw values (`*_at`), not preformatted strings, so the
-- app renders them in the reader's locale. The English fallback prose keeps
-- its existing to_char() formatting.

-- ── bid_received  [patched from 20260702_notifications.sql] ──
create or replace function public.notify_bid_received()
returns trigger language plpgsql security definer
set search_path = public
as $$
declare
  v_employer_id uuid;
  v_shift_title text;
begin
  select employer_id, title into v_employer_id, v_shift_title
  from public.shifts
  where id = new.shift_id;

  if v_employer_id is not null then
    insert into public.notifications (user_id, type, title, body, link, params)
    values (
      v_employer_id,
      'bid_received',
      'New bid received',
      'Someone applied for "' || coalesce(v_shift_title, 'your shift') || '".',
      '/employer/shifts/' || new.shift_id,
      jsonb_build_object('shift_title', coalesce(v_shift_title, 'your shift'))
    );
  end if;

  return null;

exception when others then
  raise warning 'notify_bid_received failed: %', sqlerrm;
  return null;
end;
$$;

-- ── bid_accepted / bid_rejected  [patched from 20260702_notifications.sql] ──
create or replace function public.notify_bid_status_change()
returns trigger language plpgsql security definer
set search_path = public
as $$
declare
  v_shift_title text;
begin
  select title into v_shift_title
  from public.shifts
  where id = new.shift_id;

  insert into public.notifications (user_id, type, title, body, link, params)
  values (
    new.worker_id,
    case when new.status = 'accepted' then 'bid_accepted' else 'bid_rejected' end,
    case when new.status = 'accepted' then 'Bid accepted' else 'Bid rejected' end,
    case
      when new.status = 'accepted' then 'Your bid for "' || coalesce(v_shift_title, 'a shift') || '" was accepted.'
      else 'Your bid for "' || coalesce(v_shift_title, 'a shift') || '" was rejected.'
    end,
    '/worker/shifts/' || new.shift_id,
    jsonb_build_object('shift_title', coalesce(v_shift_title, 'a shift'))
  );

  return null;

exception when others then
  raise warning 'notify_bid_status_change failed: %', sqlerrm;
  return null;
end;
$$;

-- ── shift_offer  [patched from 20260705_hiring_workflow.sql] ──
create or replace function public.notify_shift_offer()
returns trigger language plpgsql security definer
set search_path = public
as $$
declare
  v_shift_title text;
begin
  if new.status = 'offered' and old.status is distinct from 'offered' then
    select title into v_shift_title from public.shifts where id = new.shift_id;
    insert into public.notifications (user_id, type, title, body, link, params)
    values (
      new.worker_id,
      'shift_offer',
      'You''ve been selected!',
      'You were selected for "' || coalesce(v_shift_title, 'a shift') ||
        '". Please confirm or decline before ' ||
        to_char(new.offer_expires_at, 'DD Mon HH24:MI') || '.',
      '/worker/applications/' || new.id,
      jsonb_build_object(
        'shift_title', coalesce(v_shift_title, 'a shift'),
        'deadline_at', new.offer_expires_at
      )
    );
  end if;
  return null;

exception when others then
  raise warning 'notify_shift_offer failed: %', sqlerrm;
  return null;
end;
$$;

-- ── offer_declined_or_expired  [patched from 20260705_hiring_workflow.sql] ──
create or replace function public.notify_offer_response()
returns trigger language plpgsql security definer
set search_path = public
as $$
declare
  v_shift_title text;
  v_employer_id uuid;
  v_worker_name text;
begin
  if old.status = 'offered' and new.status in ('rejected', 'expired') then
    select s.title, s.employer_id into v_shift_title, v_employer_id
    from public.shifts s where s.id = new.shift_id;
    select full_name into v_worker_name from public.profiles where id = new.worker_id;

    if v_employer_id is not null then
      insert into public.notifications (user_id, type, title, body, link, params)
      values (
        v_employer_id,
        'offer_declined_or_expired',
        'Pick a substitute',
        coalesce(v_worker_name, 'A worker') || ' ' ||
          (case when new.status = 'expired' then 'did not respond in time for' else 'declined' end) ||
          ' "' || coalesce(v_shift_title, 'your shift') || '". Choose another applicant.',
        '/employer/shifts/' || new.shift_id,
        jsonb_build_object(
          'shift_title', coalesce(v_shift_title, 'your shift'),
          'worker_name', coalesce(v_worker_name, 'A worker'),
          'variant', case when new.status = 'expired' then 'expired' else 'declined' end
        )
      );
    end if;
  end if;
  return null;

exception when others then
  raise warning 'notify_offer_response failed: %', sqlerrm;
  return null;
end;
$$;

-- ── not_selected  [patched from 20260717g_guard_application_status_transitions.sql] -- no exception handler:
--    this also rejects every remaining applicant; swallowing a failure
--    would strand workers in 'pending' on a full shift.
create or replace function public.notify_not_selected_when_filled()
returns trigger language plpgsql security definer
set search_path = public
as $$
declare
  v_headcount int;
  v_accepted_count int;
  v_shift_title text;
begin
  if new.status = 'accepted' and old.status is distinct from 'accepted' then
    select headcount, title into v_headcount, v_shift_title
    from public.shifts where id = new.shift_id;

    select count(*) into v_accepted_count
    from public.applications
    where shift_id = new.shift_id and status = 'accepted';

    if v_accepted_count >= v_headcount then
      insert into public.notifications (user_id, type, title, body, link, params)
      select
        a.worker_id,
        'not_selected',
        'Not selected this time',
        'The shift "' || coalesce(v_shift_title, 'you applied for') || '" has been fully staffed. You were not selected.',
        '/worker/applications/' || a.id,
        jsonb_build_object('shift_title', coalesce(v_shift_title, 'you applied for'))
      from public.applications a
      where a.shift_id = new.shift_id
        and a.status in ('pending', 'shortlisted');

      perform set_config('app.application_status_trusted_write', 'true', true);

      update public.applications
      set status = 'rejected', updated_at = now()
      where shift_id = new.shift_id
        and status in ('pending', 'shortlisted');

      perform set_config('app.application_status_trusted_write', 'false', true);
    end if;
  end if;
  return null;
end;
$$;

-- ── shift_cancellation_choice_pending  [patched from 20260717h_fix_cancellation_payout_hours_and_tz.sql] -- no handler:
--    also stamps cancellation_choice_deadline, which is what entitles
--    the worker to a payout.
create or replace function public.notify_cancellation_choice_pending()
returns trigger language plpgsql security definer
set search_path = public
as $$
begin
  if new.status = 'cancelled' and old.status is distinct from 'cancelled'
     and new.start_at is not null and new.start_at - now() <= interval '24 hours' then

    perform set_config('app.cancellation_trusted_write', 'true', true);

    update public.applications
    set cancellation_choice_deadline = new.start_at
    where shift_id = new.id
      and status = 'accepted'
      and worker_signed_at is not null
      and cancellation_choice_deadline is null;

    insert into public.notifications (user_id, type, title, body, link, params)
    select
      a.worker_id,
      'shift_cancellation_choice_pending',
      'Shift cancelled — choose your payout',
      'The shift "' || coalesce(new.title, 'a shift') || '" was cancelled less than 24 hours before it started. ' ||
        'Choose to sign a 50% cancellation payout, or show up in person for 100% of your agreed wage. ' ||
        'Respond by ' || to_char(new.start_at at time zone 'Asia/Kuala_Lumpur', 'DD Mon HH24:MI') || '.',
      '/worker/applications/' || a.id,
      jsonb_build_object(
        'shift_title', coalesce(new.title, 'a shift'),
        'deadline_at', new.start_at
      )
    from public.applications a
    where a.shift_id = new.id
      and a.status = 'accepted'
      and a.worker_signed_at is not null
      and a.cancellation_choice_deadline = new.start_at;
  end if;
  return null;
end;
$$;

-- ── shift_cancellation_choice_made  [patched from 20260717h_fix_cancellation_payout_hours_and_tz.sql] -- no handler:
--    this function's main job is writing the payout row. Everything
--    except the notification INSERT is byte-identical to 20260717h_fix_cancellation_payout_hours_and_tz.sql.
create or replace function public.create_cancellation_payout()
returns trigger language plpgsql security definer
set search_path = public
as $$
declare
  v_shift record;
  v_hours numeric;
  v_multiplier numeric;
  v_reason text;
begin
  if (new.cancellation_choice = 'contract_50' and old.cancellation_choice is distinct from 'contract_50')
     or (new.cancellation_choice = 'show_up_100' and new.cancellation_proof_path is not null and old.cancellation_proof_path is null) then

    select s.employer_id, s.start_at, s.end_at, s.title, s.status, s.occurrences into v_shift
    from public.shifts s where s.id = new.shift_id;

    -- Defense-in-depth: never create a payout unless the shift is actually
    -- cancelled and this application was actually accepted + contract-signed,
    -- regardless of which RLS policy or trigger path authorized the write
    -- that landed us here.
    if v_shift.status is distinct from 'cancelled'
       or new.status is distinct from 'accepted'
       or new.worker_signed_at is null then
      return null;
    end if;

    -- Total contracted hours across every occurrence (one application covers
    -- the whole multi-day set), overnight occurrences wrapping +24h — the
    -- SQL mirror of the app's occurrenceHours/totalOccurrenceHours helpers.
    select coalesce(sum(
             case
               when mins > 0 then mins
               else mins + 24 * 60
             end
           ) / 60.0, 0)
    into v_hours
    from (
      select (split_part(o->>'end', ':', 1)::int * 60 + split_part(o->>'end', ':', 2)::int)
           - (split_part(o->>'start', ':', 1)::int * 60 + split_part(o->>'start', ':', 2)::int) as mins
      from jsonb_array_elements(coalesce(v_shift.occurrences, '[]'::jsonb)) o
      where o ? 'start' and o ? 'end'
    ) x;

    if v_hours <= 0 then
      v_hours := extract(epoch from (v_shift.end_at - v_shift.start_at)) / 3600.0;
    end if;
    v_hours := greatest(0.25, v_hours);

    if new.cancellation_choice = 'contract_50' then
      v_multiplier := 0.5;
      v_reason := 'late_cancellation_50pct';
    else
      v_multiplier := 1.0;
      v_reason := 'late_cancellation_show_up_100pct';
    end if;

    if new.cancellation_choice_made_at is null then
      perform set_config('app.cancellation_trusted_write', 'true', true);
      update public.applications set cancellation_choice_made_at = now() where id = new.id;
    end if;

    insert into public.payout_item (
      payout_cycle_id, worker_id, employer_id, amount, currency, scheduled_date,
      status, source_refs, idempotency_key
    ) values (
      null, new.worker_id, v_shift.employer_id,
      round(new.wage_ask * v_hours * v_multiplier, 2), 'MYR', current_date,
      'queued',
      jsonb_build_object('application_id', new.id, 'shift_id', new.shift_id, 'reason', v_reason),
      'cancellation:' || new.id::text
    )
    on conflict (idempotency_key) do nothing;

    insert into public.notifications (user_id, type, title, body, link, params)
    values (
      v_shift.employer_id,
      'shift_cancellation_choice_made',
      'Worker responded to shift cancellation',
      case when new.cancellation_choice = 'contract_50'
        then 'A worker accepted the 50% cancellation payout for "' || coalesce(v_shift.title, 'your shift') || '".'
        else 'A worker is showing up for "' || coalesce(v_shift.title, 'your shift') || '" and has submitted proof for full pay.'
      end,
      '/employer/shifts/' || new.shift_id,
      jsonb_build_object(
        'shift_title', coalesce(v_shift.title, 'your shift'),
        'variant', case when new.cancellation_choice = 'contract_50'
                        then 'contract_50' else 'show_up_100' end
      )
    );
  end if;
  return null;
end;
$$;

-- ── shift_checkout_submitted  [patched from 20260726d_cap_checkout_hours_to_contracted.sql] -- RPC, no handler:
--    called directly by the app, which surfaces its errors to the user.
create or replace function public.worker_submit_checkout(
  p_application_id uuid,
  p_hours numeric,
  p_break_minutes int,
  p_note text
)
returns public.applications
language plpgsql
security definer
set search_path = public
as $$
declare
  v_app record;
  v_contracted_hours numeric;
begin
  select a.id, a.worker_id, a.shift_id, a.status, a.checked_in_at, a.checked_out_at,
         a.employer_hours_confirmed_at, a.employer_hours_disputed
  into v_app
  from public.applications a
  where a.id = p_application_id
  for update;

  if v_app.id is null then
    raise exception 'Application not found';
  end if;

  if v_app.worker_id is distinct from auth.uid() then
    raise exception 'Not authorized';
  end if;

  if v_app.status is distinct from 'accepted' or v_app.checked_in_at is null then
    raise exception 'Cannot check out before checking in';
  end if;

  if v_app.checked_out_at is not null and not v_app.employer_hours_disputed then
    raise exception 'Checkout already submitted';
  end if;

  if p_hours is null or p_hours <= 0 or p_hours > 100 then
    raise exception 'Enter a valid number of hours';
  end if;

  v_contracted_hours := public.shift_contracted_hours(v_app.shift_id);
  if v_contracted_hours > 0 and p_hours > v_contracted_hours * 1.5 then
    raise exception 'Reported hours (%) exceed 150%% of the shift''s scheduled duration (% h). Contact support if you worked significant overtime.', p_hours, v_contracted_hours;
  end if;

  perform set_config('app.attendance_trusted_write', 'true', true);
  update public.applications
  set checked_out_at = now(),
      worker_reported_hours = round(p_hours, 2),
      worker_reported_break_minutes = greatest(coalesce(p_break_minutes, 0), 0),
      worker_checkout_note = nullif(trim(coalesce(p_note, '')), ''),
      employer_hours_confirmed_at = null,
      employer_hours_disputed = false,
      employer_hours_dispute_note = null
  where id = p_application_id
  returning * into v_app;

  insert into public.notifications (user_id, type, title, body, link, params)
  select s.employer_id, 'shift_checkout_submitted', 'Worker submitted checkout hours',
    'A worker reported ' || round(p_hours, 2) || ' hours for "' || coalesce(s.title, 'a shift') || '". Please confirm or dispute.',
    '/employer/shifts/' || v_app.shift_id,
    jsonb_build_object('shift_title', coalesce(s.title, 'a shift'), 'hours', round(p_hours, 2))
  from public.shifts s where s.id = v_app.shift_id;

  return v_app;
end;
$$;

revoke all on function public.worker_submit_checkout(uuid, numeric, int, text) from public;
grant execute on function public.worker_submit_checkout(uuid, numeric, int, text) to authenticated;

-- ── shift_checkout_disputed  [patched from 20260726b_guard_applications_attendance_columns.sql] -- RPC, no handler.
create or replace function public.employer_dispute_checkout(p_application_id uuid, p_note text)
returns public.applications
language plpgsql
security definer
set search_path = public
as $$
declare
  v_app record;
  v_employer_id uuid;
begin
  select a.id, a.shift_id, a.worker_id, a.checked_out_at into v_app
  from public.applications a where a.id = p_application_id for update;

  if v_app.id is null then
    raise exception 'Application not found';
  end if;

  select employer_id into v_employer_id from public.shifts where id = v_app.shift_id;
  if v_employer_id is distinct from auth.uid() then
    raise exception 'Not authorized';
  end if;

  if v_app.checked_out_at is null then
    raise exception 'No checkout submitted yet';
  end if;

  perform set_config('app.attendance_trusted_write', 'true', true);
  update public.applications
  set employer_hours_disputed = true,
      employer_hours_dispute_note = nullif(trim(coalesce(p_note, '')), ''),
      employer_hours_confirmed_at = null
  where id = p_application_id;

  insert into public.notifications (user_id, type, title, body, link, params)
  select v_app.worker_id, 'shift_checkout_disputed', 'Employer disputed your checkout hours',
    coalesce('Reason: ' || nullif(trim(coalesce(p_note, '')), ''), 'The employer disputed the hours you reported. Please resubmit.'),
    '/worker/applications/' || v_app.id,
    jsonb_build_object(
      'reason', nullif(trim(coalesce(p_note, '')), ''),
      'variant', case when nullif(trim(coalesce(p_note, '')), '') is null
                      then 'no_reason' else 'with_reason' end
    );

  if not exists (
    select 1 from public.disputes
    where application_id = v_app.id and category = 'hours_disputed' and status = 'open'
  ) then
    insert into public.disputes (application_id, filed_by, filed_by_role, category, description)
    values (
      v_app.id, auth.uid(), 'employer', 'hours_disputed',
      coalesce(nullif(trim(coalesce(p_note, '')), ''), 'Employer disputed worker-reported checkout hours.')
    );
  end if;

  select * into v_app from public.applications where id = p_application_id;
  return v_app;
end;
$$;

revoke all on function public.employer_dispute_checkout(uuid, text) from public;
grant execute on function public.employer_dispute_checkout(uuid, text) to authenticated;
